# Generated by Django 4.0.3 on 2022-03-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0001_initial'),
    ]

    operations = [
    ]
